#!/bin/bash
gcc -g -Wall -std=gnu99 otp_enc_d.c snd_recv_help.c -o otp_enc_d
gcc -g -Wall -std=gnu99 otp_enc.c snd_recv_help.c -o otp_enc
gcc -g -Wall -std=gnu99 otp_dec_d.c snd_recv_help.c -o otp_dec_d
gcc -g -Wall -std=gnu99 otp_dec.c snd_recv_help.c -o otp_dec
gcc -g -Wall -std=gnu99 keygen.c -o keygen
rm -rf *.dSYM

