#!/bin/bash
#Matrix

#Verify if matrix is from stdin or argument
TMP1="tempfile$$"

function saveMatrixOne(){
# NAME: saveMatrix - Save a matrix to a temporary file
# If there are no arguments, then it is assumed data is passed by stdin
# Save stdin to a temporary file for easier manipulation.
# This particular step can be refactored for better optimization later
if [ "$#" = "0" ]; then
	while read num 
	do
		echo "$num" >> $TMP1
	done < /dev/stdin
	Matrix=$TMP1
else
	echo "This didn't work"
	Matrix=$1
fi
}
echo "Matrix is $Matrix"
saveMatrixOne $1

#First, find the number of columns in the file.
nCols=$(head -n 1 $Matrix | wc -w)

#Second, find the number of rows
nRows=$( cat $Matrix | wc -l)

echo "$nCols $nRows"
echo "Number of Cols is: $nCols"
echo "Number of Rows is: $nRows"

if [ -a $TMP1 ]; then
	exec rm -f "$TMP1"
fi
