#!/bin/bash
#Matrix

function tempCreate(){
# Name: tempcreate
# Purpose: Creates the temporary file names
TMP="temp$$"
TMPCol="tempcol$$"
TMPRow="temprow$$"

# These variables store the inputs and outputs for function
inOne=0
inTwo=0
outOne=0
outTwo=0
}

function tempclean(){
# Name: tempclean
# Purpose: Checks for the temporary file(s) and deletes if they exist.

if [ -a $TMP ]; then
	exec rm -f "$TMP"
fi

if [ -a $TMPCol ]; then
	exec rm -f "$TMPCol"
fi

if [ -a $TMPRow ]; then
	exec rm -f "$TMPRow"
fi
}

function stdinSave(){
# NAME: stdinSave - Save a matrix to a temporary file
# If there are no arguments, then it is assumed data is passed by stdin
# Save stdin to a temporary file for easier manipulation.
# This particular step can be refactored for better optimization later
if [ "$#" = "0" ]; then
	while read num 
	do
		echo "$num" > $TMP
	done < /dev/stdin
	MatrixOne=$TMP
else
	MatrixOne=$1
fi

# Determine the Number of Columns and Number of rows
# In the Matrix
nCols=$(head -n 1 $MatrixOne | wc -w)
nRows=$( cat $MatrixOne | wc -l)
}

function divide(){
# NAME: divide - Property divides two numbers
# INPUT: Two numbers in inOne and inTwo
# OUTPUT: Division result (integer) in outOne

inOne=$1
inTwo=$2

if [ $inOne -gt "0" ]; then
	outOne="$((($inOne + ($inTwo / 2)) / $inTwo))"
else
	outOne="$((($inOne - ($inTwo / 2)) / $inTwo))"
fi

echo $outOne

}


function matrixAvg(){
# Matrix Average: Determines the average of whatever matrix file
# name is input in argument 1
# The average is sent to stdOut

input=$1

#First, find the number of columns in the file.
nCol=$(head -n 1 $input | wc -w)
sum=0
size=0

while IFS=$'\t' read -r -a myArray
do
	for i in "${myArray[@]}"
	do
		sum=$(expr $sum + $i)
		((size++))
	done
done < $input

outOne=$(divide $sum $size)
echo $outOne
}

function mean(){
tempCreate
stdinSave $1

#First, find the number of columns in the file.
sum=0
size=0

# Save each column to a temporary file
# Then Sum all numbers in temporary file
# and Output the Sum

for ((i=1; i<=$nCols; i++))
	do
		cut -d$'\t' "-f$i" $MatrixOne >> $TMPCol
		tempSave=$(matrixAvg $TMPCol)
		printf	"%s" "$tempSave"
		if [ $i -ne $nCols ]; then
			printf "\t"
		else
			echo
		fi
	done

tempclean		
}


function dims(){
tempCreate
stdinSave $1

echo "$nCols $nRows"
tempclean
}

$1 "${@:2}"
